/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ROT.h
**     Project     : PAIND
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.072, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-10-17, 22:50, # CodeGen: 39
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : ROT
**          SDK                                            : KSDK1
**          Turned On with initialization                  : yes
**          HW Interface                                   : 
**            Anode on port side, HIGH is ON               : no
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**          Shell                                          : Disabled
**     Contents    :
**         On         - void ROT_On(void);
**         Off        - void ROT_Off(void);
**         Neg        - void ROT_Neg(void);
**         Get        - uint8_t ROT_Get(void);
**         Put        - void ROT_Put(uint8_t val);
**         SetRatio16 - void ROT_SetRatio16(uint16_t ratio);
**         Deinit     - void ROT_Deinit(void);
**         Init       - void ROT_Init(void);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013-2016, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file ROT.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup ROT_module ROT module documentation
**  @{
*/         

#ifndef __ROT_H
#define __ROT_H

/* MODULE ROT. */
#ifndef __HIWARE__ /* Hiware compiler (S08, S12) only supports C89 */
  #include <stdint.h>
#endif
/* Include inherited beans */
#include "KSDK1.h"
#include "LEDpin1.h"

#if KSDK1_SDK_VERSION_USED == KSDK1_SDK_VERSION_NONE
  /* Include shared modules, which are used for whole project */
  #include "PE_Types.h"
  #include "PE_Error.h"
  #include "PE_Const.h"
  #include "IO_Map.h"
  #include "Cpu.h"
#endif


#define ROT_ClrVal()    LEDpin1_ClrVal() /* put the pin on low level */
#define ROT_SetVal()    LEDpin1_SetVal() /* put the pin on high level */
#define ROT_SetInput()  LEDpin1_SetInput() /* use the pin as input pin */
#define ROT_SetOutput() LEDpin1_SetOutput() /* use the pin as output pin */

#define ROT_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define ROT_On() LEDpin1_ClrVal()
/*
** ===================================================================
**     Method      :  ROT_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define ROT_Off() LEDpin1_SetVal()
/*
** ===================================================================
**     Method      :  ROT_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define ROT_Neg() LEDpin1_NegVal()
/*
** ===================================================================
**     Method      :  ROT_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define ROT_Get() (!(LEDpin1_GetVal()))
/*
** ===================================================================
**     Method      :  ROT_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

void ROT_Init(void);
/*
** ===================================================================
**     Method      :  ROT_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define ROT_Put(val)  ((val) ? ROT_On() : ROT_Off())
/*
** ===================================================================
**     Method      :  ROT_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void ROT_Deinit(void);
/*
** ===================================================================
**     Method      :  ROT_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void ROT_SetRatio16(uint16_t ratio);
/*
** ===================================================================
**     Method      :  ROT_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END ROT. */

#endif
/* ifndef __ROT_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
